### ISSUE TITLE
Exclude some styles that comes from packages - Next.Js

### ISSUE THREAD

**Issue by SarkarKurdish** [elchininet/postcss-rtlcss#115]
Hello, I have installed this package [React-Phone-Input-2](https://www.npmjs.com/package/react-phone-input-2) the package have a css file which I have to import it to my application, when going rtl mode for some reason the package's style brakes, I don't want to fix the break i'd rather want to the package stay with the style it currently have and I don't want rtl mode for this package at all, that why I want to postcss-rtlcss exclude this package.

Thanks

**Comment by elchininet** [comment]
Hi @SarkarKurdish,

Basically, this plugin doesn‘t have any context about the files that you are processing with `postcss-loader`. It just receives a CSS string from `postcss` as input and return it already transformed. You need to manage by your own which files are processed by which loaders. Check [this thread](https://github.com/elchininet/postcss-rtlcss/issues/68), it is a duplicated of yours.

One solution that came to my mind is to use [Rule.resourceQuery](https://webpack.js.org/configuration/module/#ruleresourcequery). So depending on the query you can apply the loaders that you want (excluding `postcss-rtlcss` from the plugins of `postcss-loader`). Something like:

```typescript
import './path_to_extrenal_css/my_library.css?no-rtl'
```

Regrads

**Comment by SarkarKurdish** [comment]
Thanks, unfortunately I could not make the code above works, I've added the module object but next js did not recognize it and throw a warning in the console I'll attack both of the images, the article that you have linked is webpack which I don't think is suitable in my situation 

![image](https://user-images.githubusercontent.com/37934074/149115975-fb65e7c4-7519-4925-8b7b-b8e5a6441711.png)


![image](https://user-images.githubusercontent.com/37934074/149115692-d7c24de3-1f88-4de7-bab5-7ac6b92527f0.png)

**Comment by elchininet** [comment]
Hi @SarkarKurdish,

That configuration should not be inside the postcss config but [inside the custom Webpack configuration of Next.js](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config).

Another workaround that came to my mind [is this one](https://github.com/elchininet/nextjs-postcss-rtlcss-example/commit/7785fb4c8d7231b1e5eafda66218982dc21379b2). I think that it would be easier for you, you can checkout that branch to test it. Basically, there is a `SCSS` file that import the external CSS but wrapped in `rtl:ignore` rules. As `SASS` is compiled first, that CSS is included in the `SASS` file and after is sent to `postcss` but with the comments already inserted, so anything between these comments will be ignored by `postcss-rtlcss`.

Try it out.

Regards

**Comment by SarkarKurdish** [comment]
Thanks for the second tip I would like to use the second one, but one problem is the way we write comment on sass since I can't use sass interpolation outside a rule I don't this that I can wrap the import around it please refer to this issue we closed yesterday #114

![image](https://user-images.githubusercontent.com/37934074/149143792-a1fad418-7c25-4f02-91f3-9e6e10941030.png)

**Comment by elchininet** [comment]
Hey @SarkarKurdish,

Don‘t use an interpolation there, this is only needed for comments inside declarations. You just eed to put a regular comment with this format `/*! coment */`. Check how it is done [in the commit that I posted before](https://github.com/elchininet/nextjs-postcss-rtlcss-example/commit/7785fb4c8d7231b1e5eafda66218982dc21379b2#diff-9da82453c957a98edd6ad1c12d340f7a331e6b919ada0aa7fb267c6024350ae0R1).

Regards.

**Comment by SarkarKurdish** [comment]
Hey @elchininet  sorry for the late response, unfortunately I couldn't get it working

![image](https://user-images.githubusercontent.com/37934074/149280933-b6465dd7-0b0a-449e-bfbd-295b6a58ff4f.png)

the background color stayed the same in both ltr an rtl 

i've also tried importing the file still didn't work

![image](https://user-images.githubusercontent.com/37934074/149281093-0aa23e4d-4230-4cef-a4df-a7843048878b.png)

**Comment by elchininet** [comment]
Hi @SarkarKurdish,

I think that you misunderstood multiple things. Your issue was that you were not able to ignore an external file being processed by `postcss-rtlss` (in this case a CSS from [React-Phone-Input-2](https://www.npmjs.com/package/react-phone-input-2)). This can be managed in different ways not related to this library because this library doesn‘t have any context about file paths or names. I gave you [a possible solution](https://github.com/elchininet/nextjs-postcss-rtlcss-example/commit/7785fb4c8d7231b1e5eafda66218982dc21379b2#diff-9da82453c957a98edd6ad1c12d340f7a331e6b919ada0aa7fb267c6024350ae0R1). If you go to that repo and checkout that branch you will see that `bootstrap` CSS is completely ignored by `postcss-rtlcss` so no `ltr` and `rtl` rules are generated for this library.

Now, the second topic:

What you are mentioning in your previous comment [was covered here](https://github.com/elchininet/postcss-rtlcss/issues/114#issuecomment-1008294135). Try to read [the documentation](https://github.com/elchininet/postcss-rtlcss#rtlignore) and understand the examples.

The next code does nothing: ([Please, check this example](https://elchininet.github.io/postcss-rtlcss/#61e021beb51f3))

```css
/*! rtl:begin:ignore */
body {
    background-color: darkcyan;
}
/*! rtl:end:ignore */
```

It is the same as writing:

```css
body {
    background-color: darkcyan;
}
```

It is just a code that changes the background color of your page without taking into account the direction of it.

`/* rtl:ignore */` directives do nothing there because there is nothing to be flipped, so there is nothing to ignore (`background-color` is not a property that will be flipped changing the direction of the page). If you want different background colours per direction, use the [/*rtl:{value}*/ directive](https://github.com/elchininet/postcss-rtlcss#rtlvalue) as I showed you [in the previous issue](https://github.com/elchininet/postcss-rtlcss/issues/114#issuecomment-1008294135).

Regards.

**Comment by elchininet** [comment]
Hi @SarkarKurdish,
It seems that you already solved your problem. Closing this issue.
Please, open a new one if you have any other problem.
Regards.

**Comment by SarkarKurdish** [comment]
@elchininet I'm sorry for some reason I just forgot about this issue, right after posting my last comment I realized what was my mistake, `/* rtl:ignore */` this does not remove the code from my css file, it just don't flip the values that's where I was wrong. after exclude my styles from `rtlcss` the file did not flipped to `rtl` yet there were still issue like this in the image

![image](https://user-images.githubusercontent.com/37934074/151698036-8e1610e2-63bb-4d40-9ef5-bb9d4cfad144.png)

I found out that was not because of the rtlcss file rather because I've changed the whole document's direction so adding a div parent to my phone components and force it to use `ltr` direction fixed the issue

![image](https://user-images.githubusercontent.com/37934074/151698103-35196f59-0eeb-475b-b8c3-f08c0950093c.png)
![image](https://user-images.githubusercontent.com/37934074/151698108-d4fa370d-e5d4-4c11-8138-a3d4ceddaff2.png)


Thanks for the help.

**Comment by elchininet** [comment]
Thanks for the update @SarkarKurdish, I‘m glad that you solved it.
Regards.
