### ISSUE TITLE
Is it possible to use this plugin with Storybook?

### ISSUE THREAD

**Issue by mrkesh** [elchininet/postcss-rtlcss#141]
Spent hours trying to come up with a setup that allowed me to run Storybook and my components and an enhanced version of my inlined CSS (Storybook seems to use Emotion) to have RTL support, but nothing that I tried worked.

Among other things, this is what I have in my `package.json`:
```
"@storybook/addon-postcss": "^2.0.0", // may or not be needed, tried with and without
"postcss": "^8.4.12",
"postcss-loader": "4.2.0",
"postcss-rtlcss": "^3.6.2",
"rtlcss": "^3.5.0",
```

I managed to load Storybook, but inlined styles do not contain a RTL version. Has anyone managed to have a setup w/ Storybook+postcss-rtlcss?

**Comment by elchininet** [comment]
Hi @mrkesh,

This plugin is intended to be used as a `postcss` plugin, so as far as you manage to make `postcss` working in your project, this plugin should do the proper transformations to the processed CSS. So, you should try to make `postcss` process your CSS first, the plugins that you hook into `postcss` should be a second step. I can try to help you with your tasks or point you out in the right direction.

With "inline styles", are you referring to styles directly in HTML elements with the `style` property? Because the intention of `@storybook/addon-postcss` or `postcss` is not to transform those.

It is better if you provide a repo with your configuration to understand better what you are trying to do and which CSS is not processed.

Regards.

**Comment by mrkesh** [comment]
Hey @elchininet ,

Thanks for the prompt reply. Your plugin is actually working as intended. The issue actually stemmed from the complicated Storybook setup where you have to hack your way around to enable PostCSS plugins.

[This post](https://github.com/storybookjs/presets/issues/131#issuecomment-932282725) really helped me to setup `postcss-rtlcss` with `Storybook`.

In case someone stumbled across a similar issue, here's my setup.


**Storybook's main.js**
```
module.exports = {
  stories: ['../src/components/**/*.stories.[tj]s'],
  typescript: {
    check: true,
    reactDocgen: 'react-docgen-typescript',
    reactDocgenTypescriptOptions: {
      skipChildrenPropWithoutDoc: false,
      shouldExtractLiteralValuesFromEnum: true,
    },
  },
  addons: [
    {
      name: '@storybook/preset-scss',
      options: {
        cssLoaderOptions: {
          modules: true,
        },
      },
    },
    {
      name: '@storybook/addon-postcss',
      options: {
        postcssLoaderOptions: {
          implementation: require('postcss'),
        },
      },
    },
    // Other storybook addons
  webpackFinal: async (config) => {
    // Whichever setup you have...and then the following...

    const cssRule = config.module.rules.find((rule) => rule.test && rule.test.test('.css'));
    const sassRule = config.module.rules.find((rule) => rule.test && rule.test.test('.scss'));
    const sassLoaderIndex = sassRule.use.findIndex(
      ({ loader }) => loader && loader.includes('sass-loader'),
    );
    const postCSSLoader = cssRule.use.find(
      ({ loader }) => loader && loader.includes('postcss-loader'),
    );

    postCSSLoader.options.postcssOptions = {
      plugins: [require('postcss-rtlcss')],
    };
    sassRule.use.splice(sassLoaderIndex, 0, postCSSLoader);

    return config;
  },
};
```

**Comment by elchininet** [comment]
Hi @mrkesh,
I‘m glad that you solved your issue.
Thanks for documenting your setup.
Regards
