### ISSUE TITLE
Add addPrefixToSelector option

### ISSUE THREAD

**Issue by kutnickclose** [elchininet/postcss-rtlcss#156]
Hello,

I'm migrating from `postcss-rtl` to `postcss-rtlcss`.  I was wondering if you would be open to including a `addPrefixToSelector` option similar to postcss-rtl.  https://github.com/vkalinichev/postcss-rtl#options

The main use case is that I need the css output to look like `.dir-ltr.classname` but currently the only output option is `.dir .classname` (with a space).

**Comment by elchininet** [comment]
Hi @kutnickclose,
It is a good proposal, to make it more flexible, it would requite two transformer functions, one for the normal prefixed rules and another for the safe prefixed rules.
I will implement it when I have some time.
Regards

**Comment by elchininet** [comment]
Hi @kutnickclose,

You can use [version 3.7.0 of the package](https://www.npmjs.com/package/postcss-rtlcss/v/3.7.0). The is a new option called `prefixSelectorTransformer`. There is no need for two transformers because the same transformer can holds different logics depending on the prefix used. You can consult [the documentation about its usage](https://github.com/elchininet/postcss-rtlcss#prefixselectortransformer) on the README.

Regards and thanks for your support.

**Comment by kutnickclose** [comment]
@elchininet, would it also be possible to add this to the legacy version for postscss v7?

**Comment by elchininet** [comment]
Yes, it is possible. Let me add the changes there and bump a minor version. I‘ll let you know when it is done.

**Comment by elchininet** [comment]
Hi @kutnickclose,
These changes have been included in the [legacy version 1.8.0](https://www.npmjs.com/package/postcss-rtlcss/v/1.8.0).
Regards.
