### ISSUE TITLE
Issue with padding 0 overrides in combined mode

### ISSUE THREAD

**Issue by kutnickclose** [elchininet/postcss-rtlcss#161]
Core issue in the playground:
![image](https://user-images.githubusercontent.com/6117662/180510166-213bde30-60d2-4c6a-b856-9c3f366a4da4.png)

The eventual output of the css will be 8px rather than 0px due to the specificity of the 8px being later.  Is it possible to not drop the padding value even if it's 0?

expected result:
```
.test1 {
    padding-top: 4px;
    padding-bottom: 4px;
    padding-top: 0;
    padding-bottom: 0;
    padding-left: 0;
    padding-right: 0;
}

[dir="ltr"] .test1 {
    padding-left: 8px;
    padding-right: 8px;
    padding-left: 0;
    padding-right: 0;
}

[dir="rtl"] .test1 {
    padding-right: 8px;
    padding-left: 8px;
    padding-left: 0;
    padding-right: 0;
}
```

**Comment by elchininet** [comment]
Hi @kutnickclose,
It is a bug, but the expected result of that input should be same input without changes. There is no need to create `ltr` and `rtl` prefixes in that case. I‘ll let you know when it is fixed.
Regards.

**Comment by elchininet** [comment]
Hi @kutnickclose,

With [version 3.7.1](https://www.npmjs.com/package/postcss-rtlcss/v/3.7.1) or [legacy version 1.8.1](https://www.npmjs.com/package/postcss-rtlcss/v/1.8.1) of the package, this issue is already solved. This is the result of your input:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/3728220/180646519-8c2f6c33-52a4-4ac5-b3ab-426cc120b207.png">

The `rtl` or `ltr` rules are created only if the last rules are not symmetrical:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/3728220/180646656-5ad75f79-1837-4e10-9c6f-1c28d4d5272f.png">

**Comment by kutnickclose** [comment]
Awesome. Thanks @elchininet
