### ISSUE TITLE
rtl:raw not taken into account in my final build

### ISSUE THREAD

**Issue by lauterry** [elchininet/postcss-rtlcss#265]
Hello

I use 

```
svg {
/*rtl:raw:
    transform: scaleX(-1);*/
}
```

and this is my webpack config for production build

```
{
		test: /\.scss$/,
		use: [
			MiniCssExtractPlugin.loader,
			{
				loader: "css-loader",
				options: {
					modules: "icss",
				},
			},
			{
				loader: "postcss-loader",
				options: {
					postcssOptions: {
						plugins: [
							"autoprefixer",
							enableRTL
								? postcssRTLCSS({
										mode: Mode.combined,
										})
								: "",
						],
					},
				},
			},
			{
				loader: "sass-loader",
				options: {
					additionalData: sassLoaderData,
					// Prefer `dart-sass`
					implementation: require("sass"),
				},
			},
		],
	},
```

The final build does not take the directive rtl:raw into account.

The transform css property is missing

could it be a bug ?

**Comment by elchininet** [comment]
Hi @lauterry,
Could you confirm if [this](https://elchininet.github.io/postcss-rtlcss/#65c2521d024ec) is what you expect?
If it is what you expect it seems that the issue is in your set up. In that case create a minimum reproducible example using the same tools/frameworks that you are using so I can take a look closer.
Regards

**Comment by elchininet** [comment]
Hi @lauterry,
Glad to hear that :)
Thanks!
