### ISSUE TITLE
Plugin does not work with media queries nested inside selectors 

### ISSUE THREAD

**Issue by MaciejZajac** [elchininet/postcss-rtlcss#324]
Plugin doesn't seem to add a prefix when there is a media query nested in a selector .

```
.self {
    padding: 10px 10px 14px;
}

.self {
    @media (width > 1024px) {    
        padding: 10px 10px 12px;
    }
}
```

expected:
```
[dir] .self {
    @media (--bp-laptop) {    
        padding: var(--spacing-1000) var(--spacing-400) 120px;
    }
}

[dir] .self {
    padding: var(--spacing-1000) var(--spacing-400) 120px;
}
```

actual:
```
.self {
    @media (--bp-laptop) {    
        padding: var(--spacing-1000) var(--spacing-400) 120px;
    }
}

[dir] .self {
    padding: var(--spacing-1000) var(--spacing-400) 120px;
}
```

According to this nested media is a valid css
https://github.com/postcss/postcss-nested/issues/141

Playground link
https://elchininet.github.io/postcss-rtlcss/#662f7595f2033

**Comment by elchininet** [comment]
Hi @MaciejZajac,

That is correct, putting a media-query containing only declarations inside a rule [is a valid SASS code](https://sass-lang.com/documentation/at-rules/css/). But even if this plugin [has a basic support for rules inside media-queries](https://elchininet.github.io/postcss-rtlcss/#662f89816f115) it does not do the entire job that [Dart-sass](https://sass-lang.com/dart-sass/) does, that is not the purpose of this plugin and it will never be.

`PostCSS-RTLCSS` (as well as [RTLCCS](https://rtlcss.com/)) expects that you provide an already compiled CSS input, not a native `SASS` code, so my recommendation is that you run [Dart-sass](https://sass-lang.com/dart-sass/) or any other plugin that is created to compile SASS code into `CSS` **before** running `PostCSS-RTLCSS` and not in the other way around.

Regards

**Comment by elchininet** [comment]
Hi @MaciejZajac,
I am seeing that sice December 2023, `CSS` nesting is supported by the major browsers. I'll reopen the issue but do not expect that this will be solved in a near future, my recommendation of using some tool to unwrap the nesting remains.

![image](https://github.com/elchininet/postcss-rtlcss/assets/3728220/c7bc0627-f95e-46b8-adff-03f18c48e1f4).

**Comment by louy** [comment]
Thanks @elchininet
Yes this is standard CSS syntax and not SASS as mentioned by @MaciejZajac 

Would you accept contributions to fix it? And can you give pointers on where this could be fixed in the codebase if it was to be fixed? I'd love to assess effort

**Comment by elchininet** [comment]
Thanks @louy,

I knew that the proposal was ongoing but I didn't know that the support right now is above 85% and it has become a new baseline since December.

Contributions are always welcomed, but implementing it would be a bit hard to achieve, just because the way in which the plugin works at the moment. It expects that inside an at-rule could be rules or other at-rules, but not declarations. If it the declarations parser is run inside the at-rules, then the parser itself needs to be refactored to allow this togeteher with all the store logic that expects to contain rules that needs to be flipped because their declarations were flipped (in this case they should be rules that should be flipped because any at-rule at any level inside it contains declarations that have been flipped). All of this should be done taking into account all the logic that this plugin provides to deal with overriden properties and avoid a rule being overriden because specificity of prefixed rules, in this case it should do the same but taking into account any at-rule nested inside a rule.

If you come with an easy solution to deal with this, I would be happy to discusss it help you to get it implemented.

Regards

**Comment by elchininet** [comment]
@louy,
Just take into account, as I posted before, that at the moment the plugin does support basic nesting if the at-rules contain rules instead declarations. [This is the same code](https://elchininet.github.io/postcss-rtlcss/#662f89816f115), but placing the rule inside the at-rule instead of the other way around, and as you can check it works. What doesn't not work at the moment is to have declarations inside an at-rule because which should be flipped is the nearest rule above the tree (or the rules above that one if there was some overriding).

**Comment by elchininet** [comment]
Hi @MaciejZajac and @louy,
This issue has been fixed in [the latest version of the plugin](https://www.npmjs.com/package/postcss-rtlcss/v/5.5.0).

Here is an example of multiple nested at-rules with declarations inside: https://elchininet.github.io/postcss-rtlcss/#66f884cbbce5b

Please, try it and let me know if it solves all your issues.

Regards

**Comment by louy** [comment]
Thank you so much!
